// <auto-generated/>
namespace AlgorithmPrograms
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// this is program for anagram and prime finder
    /// </summary>
    class AnagramAndPrimeProgram
    {
        /// <summary>
        /// 
        /// </summary>
        public static void AnagramAndPrime()
        {
            Utility AnagPrimeUtility = new Utility();
            Console.Write("enter a range from 1 : ");
            //its for taking the Number range from 1 to ?
            int PrimeNumberRange = int.Parse(Console.ReadLine());
            //initialize the array
            int[] PrimeArray = new int[AnagPrimeUtility.primeNumberCounter(PrimeNumberRange)];
            //Prime number array list below
            PrimeArray = AnagPrimeUtility.PrimeNumbersUtility(PrimeNumberRange);
            //to printing thee anagram as well as prime number in that range
            AnagPrimeUtility.AnagramFinder(PrimeArray);
        }
    }
}
