//<auto-generated/>
namespace AlgorithmPrograms
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// this code for finding two strings are anagram or not
    /// </summary>
    class AnagramProgram
    {
        /// <summary>
        /// 
        /// </summary>
        public static void Anagrams()
        {
            Utility AnagramUTL = new Utility();
            Console.WriteLine("Enter First String");
            string InputString1 = Console.ReadLine();
            Console.WriteLine("Enter Second String");
            string InputString2 = Console.ReadLine();
            //if return value is true then input strings are anagrams
            if (AnagramUTL.AnagramStringFinder(InputString1, InputString2) == 0)
            {
                Console.WriteLine("These are anagrams");
            }
            else
                Console.WriteLine("This are not a anagrams");

        }
    }
}
