// <auto-generated/>
namespace AlgorithmPrograms
{
	using System;
	using System.Collections.Generic;
	using System.Text;

	/// <summary>
	/// This is the Binary Word Search program
	/// </summary>
	class BinaryWordSearchProgram
    {
		public static void BinaryWordSearch()
		{
			Utility BinaryWordSearchUTL = new Utility();
			Console.WriteLine("Enter Your string to search");
			string SearchString = Console.ReadLine();
			if (BinaryWordSearchUTL.BinaryWordSearching(SearchString))
			{
				Console.WriteLine("Your string '{0}' is available",SearchString);
			}
			else
			{
				Console.WriteLine("Your String '{0}' is not available",SearchString);
			}
		}
	}
}
