//<auto-generated/>
namespace AlgorithmPrograms
{
	using System;
	using System.Collections.Generic;
	using System.Text;

	/// <summary>
	/// This is the find number program
	/// </summary>
	class FindNumberProgram
    {
		/// <summary>
		/// Finds the number.
		/// </summary>
		public static void FindNumber()
		{
			try
			{
				Utility FindNumberUTL = new Utility();
				Console.Write("Enter a number between 0: ");
				FindNumberUTL.searchNum(int.Parse(Console.ReadLine()));
			}
			catch (Exception e)
			{
				Console.WriteLine("Your Input is Wrong\nTry again...{0}",e);
			}
		}
	}
}
