//<auto-generated/>
namespace AlgorithmPrograms
{
	using System;
	using System.Collections.Generic;
	using System.Text;

	/// <summary>
	/// this is string insertion sort program
	/// </summary>
	public class InsertionSortProgram
	{
		/// <summary>
		/// This is the insertion sort
		/// </summary>
		public static void InsertionSort()
		{
			Utility insertionUtility = new Utility();
			////This is the unsorted string input
			string[] inputStringArray = { "ZZZ", "VVV", "III", "BBB", "CCC", "AAA" };
			Console.WriteLine("Your string array is [{0}]", string.Join(", ", inputStringArray));
			inputStringArray = insertionUtility.InsertionSortUtility(inputStringArray);
			Console.WriteLine("Your sorted Array");
			////This is the Sorted String Array
			for (int i = 0; i < inputStringArray.Length; i++)
			{
				Console.Write(inputStringArray[i] + ", ");
			}
		}
	}
}
