//<auto-generated/>
namespace AlgorithmPrograms
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// This is Prime Numbers program
    /// </summary>
    public class PrimeNumbersProgram
    {
        /// <summary>
        /// This is the prime number finding program
        /// </summary>
        public static void PrimeNumbers()
        {
            Utility primeUtility = new Utility();
            Console.Write("Give a input for Range 1 to ");
            int range = int.Parse(Console.ReadLine());
            ////this array contains prime number from 2 to given range
            int[] primeArr = primeUtility.PrimeNumbersUtility(range);
            Console.WriteLine("[{0}]", string.Join(", ", primeArr));
        }
    }
}