// <auto-generated/>
namespace AlgorithmPrograms
{
	using System;
	using System.Collections.Generic;
	using System.Text;

	/// <summary>
	/// This is Prime Numbers program
	/// </summary>
	class PrimeNumbersProgram
	{
		/// <summary>
		///	
		/// </summary>
		public static void PrimeNumbers()
		{
			Utility PrimeUtility = new Utility();
			Console.Write("Give a input for Range 1 to ");
			int Range = int.Parse(Console.ReadLine());
			//this array contains prime number from 2 to given range
			int[] primeArr = PrimeUtility.PrimeNumbersUtility(Range);
			Console.WriteLine("[{0}]", string.Join(", ", primeArr));
		}


	}
}
