// <auto-generated/>
namespace FunctionalPrograms
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// this is the Day of the week program
    /// </summary>
    class DayOfWeekProgram
    {
        public static void DayOfTheWeek()
        {

            Console.WriteLine("Enter Day Month Year");
            int UserDay = int.Parse(Console.ReadLine());
            int UserMonth = int.Parse(Console.ReadLine());
            int UserYear = int.Parse(Console.ReadLine());
            Utility DayOfTheWeekUTL = new Utility();
            Console.WriteLine(DayOfTheWeekUTL.DayOfTheWeekUtility(UserDay, UserMonth, UserYear));
            //System.out.println("Day is " + d.retDay());
            //System.out.println("Month is " + d.retMonth(month));
            //System.out.println("Year is " + year);
        }
    }
}
