// <auto-generated/>
namespace FunctionalPrograms
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// This is the Gambler program
    /// </summary>
    class GamblerProgram
    {
        public static void Gambler()
        {
            Utility GamblerUTL = new Utility();
            GamblerUTL.GamblerPlaying();

        }
    }
}

