// <auto-generated/>
namespace FunctionalPrograms
{
	using System;
	using System.Collections.Generic;
	using System.Text;

	/// <summary>
	/// This is the monthly payment calculating program
	/// </summary>
	class MonthlyPaymentProgram
    {
		public static void MonthlyPayment()
		{
			Utility MonthlyPayUTL = new Utility(); 
			Console.WriteLine("Enter principal amount, years, percentage "
			+ "respectively in commond line");
Start:		try
			{
				//try is used for any string values given by users it will takes the control to Start
				long PrincipalAmount = long.Parse(Console.ReadLine());
				int Years = int.Parse(Console.ReadLine());
				float Percent = float.Parse(Console.ReadLine());
				//taking user inputs are principal amount years percentage
				double Payment = MonthlyPayUTL.PaymentCalculator(PrincipalAmount, Years, Percent);
				Console.WriteLine("Employee monthly payment is {0} ",Payment);
			}
			catch (Exception)
			{
				Console.WriteLine("Invalid key\nTry Again...");
				goto Start;
			}

		}
	}
}
