// <auto-generated/>
namespace FunctionalPrograms
{
	using System;
	using System.Collections.Generic;
	using System.Text;

	/// <summary>
	/// This is the Temperature conversion program
	/// </summary>
	class TemperatureConversionProgram
    {
		public static void TemperatureConversion()
		{
			Console.WriteLine("If you know celcius enter 1 else 0 for fahrenheit");
			Utility TemperatureUTL = new Utility();
Start:		try
			{
				int Select = int.Parse(Console.ReadLine());
				//Takes the input temeperature value and call a utility function
				if (Select > 2)
				{
					Console.WriteLine("Enter Known Value");
					double TemperatureValue = double.Parse(Console.ReadLine());
					TemperatureUTL.TemperatureConversionUtility(Select, TemperatureValue);
				}
				else
				{
					Console.WriteLine("Invalid input");
					goto Start;
				}
			}
			//If any non integer value given by user it shows wrong input and goto Start
			catch (Exception)
			{
				Console.WriteLine("Wrong input");
				goto Start;
			}
		}
				
	}
}
