// <auto-generated/>
namespace FunctionalPrograms
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// This is a two dimentional array program
    /// </summary>
    class TwoDArrayProgram
    {
        public static void TwoDArray()
        {
            Utility TwoDArrayUTL = new Utility();
            Console.WriteLine("Enter Number of rows");
            int m = Int32.Parse(Console.ReadLine());
            Console.WriteLine("Enter number of columns");
            int n = Int32.Parse(Console.ReadLine());
            TwoDArrayUTL.TwoDArrayUtility(m, n);
        }
    }
}

