//<auto-generated/>
namespace AlgorithmPrograms
{
	using System;
	using System.Collections.Generic;
	using System.Text;

	/// <summary>
	/// This is Bubble sort program
	/// </summary>
	class BubbleSortProgram
	{
		/// <summary>
		/// this method takes the number of input integers and integer values stores in 
		/// array a, and call Bubble sort Utility function, display the sorted array
		/// </summary>
		public static void BubbleSortInt()
		{
			Utility BubbleUtility = new Utility();
			try
			{
				Console.WriteLine("How many Numbers you have");
				//it takes the array size from user
				int[] IntegerArray = new int[int.Parse(Console.ReadLine())];
				Console.WriteLine("Enter a {0} Values", IntegerArray.Length);
				//stores the integers in int array
				for (int i = 0; i < IntegerArray.Length; i++)
				{
					IntegerArray[i] = int.Parse(Console.ReadLine());
				}
				Console.WriteLine("Your Integer array is [{0}]", string.Join(", ", IntegerArray));
				//After sorting
				IntegerArray = BubbleUtility.IntegerBubbleSort(IntegerArray);
				Console.WriteLine("Sorted array is [{0}]", string.Join(", ", IntegerArray));
			}
			catch (Exception)
			{
				Console.WriteLine("You have entered non integer value\nTry again...");
			}

		}

	}
}
