// <auto-generated/>
namespace AlgorithmPrograms
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Text.RegularExpressions;

    /// <summary>
    /// This is the program for Regex
    /// </summary>
    class RegexCustomizeProgram
    {
        public static void RegEx()
        {
            Utility RegExUTL = new Utility();
            Console.WriteLine(RegExUTL.RegExUtility());
        }
    }
}
