//<auto-generated/>
namespace DataStructurePrograms
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// this is the calender using stack
    /// </summary>
    class CalenderStack
    {
        public static void MyStackCalenderCall()
        {
            try
            {
                Console.WriteLine("Enter a year");
Year:           int Year = int.Parse(Console.ReadLine());
                if (Year > 9999 || Year < 1000)
                {
                    Console.WriteLine("Wrong year entry");
                    goto Year;
                }
                Console.WriteLine("Enter a Month JAN=1......DEC=12");
Month:          int Month = int.Parse(Console.ReadLine());
                if (Month > 12)
                {
                    Console.WriteLine("Wrong month");
                    goto Month;
                }
                Utility CalenderUTL = new Utility();
                CalenderUTL.CalenderStackUtility(Year, Month);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
                //Console.WriteLine("You are entered Wrong input");
            }
        }
    }
}
