//<auto-generated/>
namespace DataStructurePrograms
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// this is the node class for Doubly linked list it have next and previous nodes
    /// </summary>
    /// <typeparam name="T"></typeparam>
    class NodeDoublyLinkedList<T>
    {
        public NodeDoublyLinkedList<T> Next;
        public NodeDoublyLinkedList<T> Previous;
        public T Data;
        //constructor for initization
        public NodeDoublyLinkedList(T Data)
        {
            this.Data = Data;
        }
    }
}
