//<auto-generated/>
namespace DataStructurePrograms
{
    using System;
    using System.IO;
    using System.Linq;
    using System.Collections.Generic;

    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Enter your Option\n1 for Linked List\n2 for Balanced Parentheses Program" +
                "\n3 for Bankin Queue\n4 for Palindrome checking program\n5 for Calender using 2D array" +
                "\n6 for Calender using Queue\n7 For Calender using Stack\n8 for Doubly linked list");
Home:       try
            {
                int Option = int.Parse(Console.ReadLine());
                switch (Option)
                {
                    case 1:
                        StringLinkedListProgram.StringLinkedList();
                        break;
                    case 2:
                        BalancedParenthesesProgram.BalancedParentheses();
                        break;
                    case 3:
                        BankingCashCounterProgram.ServiceSelection();
                        break;
                    case 4:
                        PalindromeCheckingProgram.PalindromeChecking();
                        break;
                    case 5:
                        MyCalender.MyCalenderCall();
                        break;
                    case 6:
                        CalenderQueue.MyQueueCalenderCall();
                        break;
                    case 7:
                        CalenderStack.MyStackCalenderCall();
                        break;
                    case 8:
                        DoublyLinkedListProgram.DoublyLinkedList();
                        break;
                    default:
                        Console.WriteLine("Wrong selection...");
                        break;
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
                Console.WriteLine("You entered invalid value\nTry again...");
                goto Home;
            }
        }
    }
}
