//<auto-generated/>
namespace DataStructurePrograms
{
    using System;
    using System.IO;
    using System.Linq;
    using System.Collections.Generic;

    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Enter your Option\n1 for Linked List");
Home:       try
            {
                int Option = int.Parse(Console.ReadLine());
                switch (Option)
                {
                    case 1:
                        StringLinkedListProgram.StringLinkedList();
                        break;
                    default:
                        Console.WriteLine("Wrong selection...");
                        break;
                }
            }
            catch (Exception)
            {
                Console.WriteLine("You entered invalid value\nTry again...");
                goto Home;
            }
        }
    }
}
