//<auto-generated/>
namespace DataStructurePrograms
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// This is doubly linked list program
    /// </summary>
    class DoublyLinkedListProgram
    {
        public static void DoublyLinkedList()
        {
            MyDoublyLinkedList<string> MyList = new MyDoublyLinkedList<string>();
            //MyList.Add("Hi");
            //MyList.Add("Hi");
            MyList.Add("Hi");
            MyList.Add("Hello");
            MyList.Add("Namaskara");
            MyList.Add("Hi");
            //MyList.Append("Hi");
            Console.WriteLine(MyList.Index("Hello"));
            MyList.Display();
            Console.WriteLine(MyList.pop(3));
            Console.WriteLine(".............");
            MyList.Display();
        }
    }
}
