//<auto-generated/>
namespace DataStructurePrograms
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// This is stack by Linked List
    /// </summary>
    class StackLinkedList
    {
        Node Top;
        //Node Top = new Node(null);
        public void push(string Data)
        {
            Node CurrentNode = Top;
            Node TempNode = new Node(Data);
            if (Top == null)
            {
                Top = TempNode;
                return;
            }

            TempNode.Next = Top;
            Top = TempNode;
        }
        //public void push(Object Value)
        //{
        //    String StrValue = Value.ToString();
        //    Node Current = Top;
        //    Node TempNode = new Node(StrValue);
        //    TempNode.Next = Top;
        //    Top = TempNode;
        //}
        public string pop()
        {
            Node CurrentNode = Top;
            string Ans;
            if (Top == null)
            {
                return "Stack is empty";
            }
            if (CurrentNode.Next == null)
            {
                Ans = Convert.ToString(CurrentNode.data);
                Top = null;
                return Ans;
            }
            Ans = Convert.ToString(Top.data);
            Top = CurrentNode.Next;
            return Ans;
        }

        public bool IsEmpty()
        {
            if (Top == null)
            {
                return true;
            }
            return false;
        }
        
        public string peek()
        {
            if (Top == null)
            {
                return "Stack is empty";
            }
            return Convert.ToString(Top.data);
        }
    }
}
