// <auto-generated/>
namespace FunctionalPrograms
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// This is the Anagram class
    /// </summary>
    class Anagram
    {

        /// <summary>
        /// in this it takes the input from user to number of strings you have
        /// and call the anagram utility function
        /// </summary>
        public static void Anagrams()
        {
            Utility AnagramUTL = new Utility();
            Console.WriteLine("Enter how many Strings you have");
            int Count = int.Parse(Console.ReadLine());
            AnagramUTL.StoringToArray(Count);
        }
    }
}
