// <auto-generated/>
namespace FunctionalPrograms
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// This is the program to find the distance between two co-ordinates
    /// </summary>
    class DistanceFind
    {
        public static void Distance()
        {
            Console.WriteLine("Enter a X point");
            int X = int.Parse(Console.ReadLine());
            Console.WriteLine("Enter a Y point");
            int Y = int.Parse(Console.ReadLine());
            double Distance = Math.Sqrt((X * X) + (Y * Y));

            Console.WriteLine("Distance from (0,0) to (" + X + "," + Y + ") = " + Distance);
        }
    }
}
