// <auto-generated/>
namespace FunctionalPrograms
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// this is class for leap year
    /// </summary>
    class LeapYearProgram
    {
        /// <summary>
        /// Leaoes the year.
        /// </summary>
        public static void LeapYear()
        {
            Home:
            Utility LeapYearUTL = new Utility();
            Console.WriteLine("Enter a year (Should be 4 digit)");
            int Year = int.Parse(Console.ReadLine());
            if(Year > 999 && Year < 10000)
            {
                //if condition satisfied enter to this statement
                //if the Given value is Leap Year then it prints 
                //else it prints  not a  leap year
                if (LeapYearUTL.IsLeapYear(Year))
                {
                    Console.WriteLine("{0} is a Leap Year", Year);
                }
                else
                    Console.WriteLine("{0} is not a leap Year", Year);
            }
            else
            {
                // if given number is not a 4 digit then it send the control to Home label
                goto Home;
            }
        }
    }
}
