// <auto-generated/>
namespace FunctionalPrograms
{
    using System;

    /// <summary>
    /// This is the main program for selecting the Functional programs
    /// </summary>
    class Program
    {

        /// <summary>
        /// Defines the entry point of the application.
        /// </summary>
        /// <param name="args">The arguments.</param>
        static void Main(string[] args)
        {
            Console.WriteLine("Enter a Option\n1 for Anagram for array of strings");
            int Option = int.Parse(Console.ReadLine());
            switch (Option)
            {
                case 1:
                    Anagram.Anagrams();
                    break;
                default:
                    Console.WriteLine("You are selecting invalid option");
                    break;
            }
        }
    }
}
