// <auto-generated/>
namespace FunctionalPrograms
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// this is the String replace program
    /// </summary>
    class StringReplaceProgram
    {

        /// <summary>
        /// String replace.
        /// </summary>
        public static void StringReplace()
        {
            String Wish = "Hello <<UserName>>, How are you?";
            Console.WriteLine("Hello Enter your name!");
            //take the input from keyboard and replace with standard string
            String Name = Console.ReadLine();
            if (Name.Length > 2)
            {
                Wish = Wish.Replace("<<UserName>>", Name);
                Console.WriteLine(Wish);
            }
            else
            {
                Console.WriteLine("You Should enter atleast 3 characters");
            }
        }

    }

}

