// <auto-generated/>
namespace FunctionalPrograms
{
	using System;
	using System.Collections.Generic;
	using System.Text;

	/// <summary>
	/// this is program to find the wind chill.
	/// </summary>
	class WindChillProgram
	{
		public static void WindChill()
		{
			Utility WindChillUTL = new Utility();
			Console.WriteLine("Enter a temperature");
			double Temperature = Int32.Parse(Console.ReadLine());
			Console.WriteLine("Enter a Velocity");
			double Velocity = Int32.Parse(Console.ReadLine());
			double Wind=WindChillUTL.WindChillUtility(Temperature,Velocity);
			if (Wind == -1)
			{
				Console.WriteLine("Your values not in range");
			}
			else
			{
				Console.WriteLine("Given temperature is " + Temperature + " Fahrenheit and Velocity is " + Velocity + " miles/hour wind chill is " + Wind);
			}
		}
	}
}
