//<auto-generated/>
namespace OrderedLinkedList
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// This is Node class for integer
    /// </summary>
    class Node
    {
        public Node Next;
        public int Data;
        public Node(int Data)
        {
            this.Data = Data;
        }
    }
}