//<auto-generated/>
namespace OrderedLinkedList
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.IO;

    /// <summary>
    /// This is the Ordered list program
    /// </summary>
    class OrderedListProgram
    {
        public static void OrderedList()
        {
            IntegerLinkedListProgram MyLinkedListIntegerUTL = new IntegerLinkedListProgram();
            string[] Separators = new string[] { " ", ",", ".", "!", "\'", " ", "\'s", "\'n" };
            string FilePath = @"D:\BridgeLabzBhush\AlgorithmPrograms\AlgorithmPrograms\bin\Debug\netcoreapp3.1\SampleInteger.txt";
            string[] StringArray = File.ReadAllLines(FilePath);
            string TempString = string.Empty;
            foreach (string Str in StringArray)
            {
                TempString += Str;
            }
            //in this section splitted at space and removes all the seperatos and added to linked list
            foreach (string EachWord in TempString.Split(Separators, StringSplitOptions.RemoveEmptyEntries))
            {
                MyLinkedListIntegerUTL.add(Convert.ToInt32(EachWord));
            }


            //MyLinkedListIntegerUTL.add(7);
            //MyLinkedListIntegerUTL.add(1);
            //MyLinkedListIntegerUTL.add(3);
            //MyLinkedListIntegerUTL.add(2);
            //MyLinkedListIntegerUTL.add(5);
            //MyLinkedListIntegerUTL.add(4);
            //MyLinkedListIntegerUTL.add(6);
            //Console.WriteLine(MyLinkedListIntegerUTL.pop(6));
            ////MyLinkedListIntegerUTL.add(1);
            //MyLinkedListIntegerUTL.remove(100);
            Console.WriteLine(MyLinkedListIntegerUTL.Index(12345));
            MyLinkedListIntegerUTL.Display();

        }
    }
}
