//<auto-generated/>
namespace OrderedLinkedList
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// this is the class for prime number 2D 
    /// </summary>
    class PrimeNumber2DProgram
    {
        public static void PrimeNumber2D()
        {
            Utility PrimeNumberUTL = new Utility();
            Console.WriteLine("You are selecting 2D array prime numbers\n1 for 1-1000 prime list" +
                "\n2 for anagram and prime list");
            try
            {
                switch (int.Parse(Console.ReadLine()))
                {
                    case 1:
                        PrimeNumberUTL.PrimeNumberUtility();
                        break;
                    case 2:
                        PrimeNumberUTL.OnlyPrimeOnlyAnagramList();
                        break;
                    default:
                        break;
                }
            }
            catch (Exception)
            {
                Console.WriteLine("You are entered Invalid Input\nTry again...");
            }
        }
    }
}
