//<auto-generated/>
namespace OrderedLinkedList
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// this is the class for prime number 2D 
    /// </summary>
    class PrimeNumber2DProgram
    {
        public static void PrimeNumber2D()
        {
            Utility PrimeNumberUTL = new Utility();
            Console.WriteLine("You are selecting 2D array prime numbers");
            try
            {
                int Range = int.Parse(Console.ReadLine());
                PrimeNumberUTL.PrimeNumberUtility();
            }
            catch (Exception)
            {
                Console.WriteLine("You are entered Invalid Input\nTry again...");
            }
        }
    }
}
