//<auto-generated/>
namespace OrderedLinkedList
{
    using System;
    using System.IO;

    /// <summary>
    /// this is the main function for Ordered Linked List
    /// </summary>
    class Program
    {
       static void Main(String[] args)
        {
            Console.WriteLine("Enter your Option\n1 for ordered linked list\n2 for Hash function" +
                "\n3 for Prime Number 2D array");
            try
            {
                int Option = int.Parse(Console.ReadLine());
                switch (Option)
                {
                    case 1:
                        OrderedListProgram.OrderedList();
                        break;
                    case 2:
                        HashingFunctionProcess.HashingProcess();
                        break;
                    case 3:
                        PrimeNumber2DProgram.PrimeNumber2D();
                        break;
                    default:
                        break;
                }
            }
            catch (Exception)
            {
                Console.WriteLine("Invalid Input\nTry again...");
            }
        }
    }

}

