//<auto-generated/>
namespace OrderedLinkedList
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.IO;

    /// <summary>
    /// This is the program for storing the hash table to file
    /// </summary>
    class SavingToFileProgram
    {
        static int Count = 0;
        public void SaveToFile(string FilePath, string[] StringArrayTemp)
        {
            TextWriter TextWriterVariable = new StreamWriter(FilePath,true);
            //this line for reference to hash key
            TextWriterVariable.Write("Values At {0}th HashKey :", Count);
            Count++;
            //save all the data in string array to file
            for(int i = 0; i < StringArrayTemp.Length; i++)
            {
                TextWriterVariable.Write(" "+StringArrayTemp[i]);
            }
            TextWriterVariable.WriteLine();
            TextWriterVariable.Close();
        }
    }
}
