//<auto-generated/>
namespace OrderedLinkedList
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// this is the stsck class is used to calling stack memory
    /// </summary>
    class UserStack
    {
        MyStack myStack = new MyStack();
        int Top = -1;

        //push to tail of the Linked list top is increased by 1
        public void push(int Data)
        {
            Top++;
            myStack.pushToStack(Data);
        }
        //pop if stack is not empty
        public int pop()
        {
            if (IsEmptyStack())
            {
                return -1;
            }
            int Ans = myStack.popFromStack();
            Top--;
            return Ans;
        }
        //if top is -1 then stackis pop
        public bool IsEmptyStack()
        {
            if(Top == -1)
            {
                return true;
            }
            return false;
        }

        //it return the stack size
        public int StackSize()
        {
            return Top + 1;
        }
    }
}
