// <auto-generated/>
namespace FunctionalPrograms
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// This is the coupon Number generation program
    /// </summary>
    class CouponNumberProgram
    {
        public static void CouponNumber()
        {
            Utility CouponUTL = new Utility();
            Console.WriteLine("Enter many coupons needed");
            int NumberOfCoupons = int.Parse(Console.ReadLine());
            CouponUTL.CouponUtility(NumberOfCoupons);
        }
    }
}

