// <auto-generated/>
namespace FunctionalPrograms
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// This is the class for finding factors.
    /// </summary>
    class FactorsProgram
    {
        /// <summary>
        /// Factors of the Number.
        /// </summary>
        public static void Factors()
        {
            Utility FactorsUTL = new Utility();
            Console.WriteLine("Enter a Number");
            int FactorsNumber = int.Parse(Console.ReadLine());
            FactorsUTL.FactrosUtility(FactorsNumber);
        }

    }
}

