// <auto-generated/>
namespace FunctionalPrograms
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// This is a program for Few Number of Notes count
    /// </summary>
    class FewNumberOfNotesProgram
    {
        public static void FewNumberOfNotes()
        {
            Utility FewNotesUTL = new Utility();
Start:      Console.WriteLine("Enter a Total Amount...");
            try
            {
                //this takes the user input
                int TotalAmount = int.Parse(Console.ReadLine());
                int TotalNotes = FewNotesUTL.NotesCount(TotalAmount);
                Console.WriteLine("Total Notes Are {0}", TotalNotes);
            }
            //if any wrong input entered by user then it sends control to start
            catch (Exception)
            {
                Console.WriteLine("Wrong input\nTry again...");
                goto Start;
            }
        }
    }
}
