// <auto-generated/>
namespace FunctionalPrograms
{
    using System;

    /// <summary>
    /// this is the Flip coin program
    /// </summary>
    class FlipCoinProgram
    {

        /// <summary>
        /// this flips the coin certain amount of the time and gives the output as head vs tails.
        /// </summary>
        public static void FlipCoin()
        {
            Utility FlipCoinUTL = new Utility();
        Home:
            Console.WriteLine("Enter a Number time you want to toss");
            int Number = FlipCoinUTL.IntInput();
            if (Number == 0)
            {
                goto Home;
            }
            float Answer = FlipCoinUTL.FlipCoinUtility(Number);
            Console.WriteLine("Heads V/S Tails percentage is " + Answer);
        }

    }
}
