// <auto-generated/>
namespace FunctionalPrograms
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// this is a class for power of two
    /// </summary>
    class PowerOfTwoProgram
    {
        /// <summary>
        /// it prints the power of two as well leap year.
        /// </summary>
        public static void PowerOfTwo()
        {
            Utility UL = new Utility();
        Home:
            Console.WriteLine("Enter a power number");
            int power = UL.IntInput();
            if (power == -1)
            {
                goto Home;
            }
            if (power >= 0 && power < 31)
            {
                for (int i = 0; i < power; i++)
                {
                    double ans = Math.Pow(2, i);
                    Console.WriteLine("2^{0} is {1} ", i, ans);
                    if (UL.IsLeapYear((int)ans) && UL.IsFourDigit((int)ans))
                    {
                        Console.WriteLine(ans + " is Leap Year");
                    }
                }
            }
        }

    }

}

