// <auto-generated/>
namespace FunctionalPrograms
{
	using System;
	using System.Collections.Generic;
	using System.Text;

	/// <summary>
	/// This is the nibble swapping Program
	/// </summary>
	class BinaryNibbleSwapProgram
    {
		public static void BinaryNibbleSwap()
		{
			Utility BinaryUtility = new Utility();
Start:		try
			{
				//Decimal Input
				Console.WriteLine("Enter Your Decimal Number");
				int DecimalNumber = int.Parse(Console.ReadLine());
				//Calls Binary Representation
				int BinaryRepresentation = (int)BinaryUtility.PositionBinary(DecimalNumber);
				Console.WriteLine("Binary Representation of your input {0}",BinaryRepresentation);
				//Here Swapping two Nibbles and perform or operation 
				int NibbleSwap = BinaryUtility.NibbleSwapping(DecimalNumber);
				Console.WriteLine("Value after nibble Swap {0}",NibbleSwap);
				Console.WriteLine("Binary Representation after Nibble swap {0}",(int)BinaryUtility.PositionBinary(NibbleSwap));
			}
			catch (Exception)
			{
				Console.WriteLine("Something is Wrong\ntry again...");
				goto Start;
			}
		}
	}
}
