// <auto-generated/>
namespace FunctionalPrograms
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// this is the Hormonic Number finding program
    /// </summary>
    class HormonicNumberProgram
    {
        /// <summary>
        /// Finding Hormonic Number 1+(1/2)+(1/3)+-----+(1/N).
        /// </summary>
        public static void Hormonic()
        {
            Utility UL = new Utility();

        Home:
            Console.WriteLine("Enter a value for finding Hormpnic Number");
            int num = UL.IntInput();
            if (num == 0)
            {
                goto Home;
            }
            Console.WriteLine(UL.HormonicUtility(num));
        }

    }
}
