// <auto-generated/>
namespace FunctionalPrograms
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// This is the program for finding Square root by using Newton's method
    /// </summary>
    class Sqrt
    {
        public static void SquareRoot()
        {
Start:      try
            {
                Console.WriteLine("Enter A number to find Square Root");
                double c = double.Parse(Console.ReadLine());
                double epsilon = 1.0e-15;  // relative error tolerance
                double t = c;              // estimate of the square root of c

                // repeatedly apply Newton update step until desired precision is achieved
                while (Math.Abs(t - c / t) > epsilon * t)
                {
                    t = (c / t + t) / 2.0;
                }

                // print out the estimate of the square root of c
                Console.WriteLine(t);
            }
            catch (Exception)
            {
                Console.WriteLine("Wrong input");
                goto Start;
            }
        }
    }
}
