//<auto-generated/>
namespace FunctionalPrograms
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// This is the Sum of zero program
    /// </summary>
    public class SumOfZeroProgram
    {
        /// <summary>
        /// Sum of zero.
        /// </summary>
        public static void SumOfZero()
        {
            Utility sumUtility = new Utility();
            Console.WriteLine("Enter a length of your array");
            try
            {
                int size = int.Parse(Console.ReadLine());
                int[] array = new int[size];
                Console.WriteLine("Enter your values");
                for (int i = 0; i < size; i++)
                {
                    array[i] = int.Parse(Console.ReadLine());
                }

                sumUtility.SumOfZeroUtility(array, size);
            }
            catch (Exception)
            {
                Console.WriteLine("You entered invalid value");
            } 
        }
    }
}
