// <auto-generated/>
namespace FunctionalPrograms
{
    using System;

    /// <summary>
    /// this is tiktactoe main program
    /// </summary>
    class TicTacToeProgram
    {
        public static void TicTacToe()
        {
            Utility UL = new Utility();
            UL.TicTakToeControl();
        }
    }
}
